server:
  port: 8888
spring:
  application:
    name: xagu-system-blog
  datasource:
    url: jdbc:mysql://192.168.189.140:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver